KS-1-5 added solution
svhanz/KotlinSprint pull request #5
Opened 2023-03-24 06:28 UTC by svhanz

2023-03-24 14:38 UTC, ievetrov requested changes

2023-03-24 14:38 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    val minute: Int = (second / 60)
Для чего тут скобки?

2023-03-24 14:38 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("Время, проведенное в космосе [минуты:секунды]: $minute:00")
С точки зрения требований задачи все правильно, секунды действительно принимают значения 0. Но если гипотетические другие разработчики (или будущий ты) поправят значение поля second, логика сломается.

Реализуй корректный подсчет секунд

2023-03-24 18:52 UTC, svhanz commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    println("Время, проведенное в космосе [минуты:секунды]: $minute:00")
Пофиксил решение.

2023-03-25 05:01 UTC, ievetrov approved these changes

2023-03-26 08:03 UTC, merged